[package]
name = "repo"
version = "0.1.0"
authors = ["Alex <busarovalex@yandex.ru>"]

[dependencies]
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
rand = "*"
